name       : python-genshi
version    : 0.7.5
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/G/Genshi/Genshi-0.7.5.tar.gz : c12d6c2abf7df0ec661d9ff2e197522eae846e43dc58abd5a36443d05bc41135
homepage   : https://genshi.edgewall.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Python toolkit for generation of output for the web
description: |
    Genshi is a Python library that provides an integrated set of components for parsing, generating, and processing HTML, XML or other textual content for output generation on the web. The major feature is a template language, which is heavily inspired by Kid.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
